// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package task

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        int32
	FirstName string
	LastName  string
	Address   pgtype.Text
}

type User struct {
	ID                int32
	Email             pgtype.Text
	PhoneNumber       string
	Otp               string
	OtpExpirationTime pgtype.Timestamp
}
